export const CASE_STATUSES = [
  "RECEIVED",
  "PARSED",
  "MANUAL_REVIEW_REQUIRED",
  "WAITING_FOR_DUE_DATE",
  "DUE_SOON",
  "OVERDUE",
  "EMAIL_REMINDER_1_SENT",
  "EMAIL_REMINDER_2_SENT",
  "PAYMENT_REQUEST_SENT",
  "CALL_SCHEDULED",
  "CALL_COMPLETED",
  "PAYMENT_PROMISED",
  "INSTALLMENT_REQUESTED",
  "INSTALLMENT_PLAN_SENT",
  "INSTALLMENT_ACTIVE",
  "INSTALLMENT_BROKEN",
  "FINAL_NOTICE_SENT",
  "READY_FOR_LEGAL_ACTION",
  "CLOSED_PAID",
  "CLOSED_CANCELLED",
  "CLOSED_UNRESOLVED"
] as const;

export type CaseStatus = (typeof CASE_STATUSES)[number];

export const TERMINAL_CASE_STATUSES: CaseStatus[] = ["CLOSED_PAID", "CLOSED_CANCELLED", "CLOSED_UNRESOLVED"];

const allowedTransitions: Record<CaseStatus, CaseStatus[]> = {
  RECEIVED: ["PARSED", "MANUAL_REVIEW_REQUIRED", "CLOSED_CANCELLED"],
  PARSED: ["WAITING_FOR_DUE_DATE", "MANUAL_REVIEW_REQUIRED", "CLOSED_CANCELLED"],
  MANUAL_REVIEW_REQUIRED: ["WAITING_FOR_DUE_DATE", "INSTALLMENT_PLAN_SENT", "FINAL_NOTICE_SENT", "CLOSED_CANCELLED"],
  WAITING_FOR_DUE_DATE: ["DUE_SOON", "OVERDUE", "CLOSED_PAID", "CLOSED_CANCELLED"],
  DUE_SOON: ["OVERDUE", "CLOSED_PAID", "CLOSED_CANCELLED"],
  OVERDUE: ["EMAIL_REMINDER_1_SENT", "PAYMENT_PROMISED", "INSTALLMENT_REQUESTED", "INSTALLMENT_PLAN_SENT", "MANUAL_REVIEW_REQUIRED", "FINAL_NOTICE_SENT", "CLOSED_PAID", "CLOSED_CANCELLED"],
  EMAIL_REMINDER_1_SENT: ["EMAIL_REMINDER_2_SENT", "PAYMENT_PROMISED", "INSTALLMENT_REQUESTED", "INSTALLMENT_PLAN_SENT", "MANUAL_REVIEW_REQUIRED", "FINAL_NOTICE_SENT", "CLOSED_PAID", "CLOSED_CANCELLED"],
  EMAIL_REMINDER_2_SENT: ["PAYMENT_REQUEST_SENT", "PAYMENT_PROMISED", "INSTALLMENT_REQUESTED", "INSTALLMENT_PLAN_SENT", "MANUAL_REVIEW_REQUIRED", "FINAL_NOTICE_SENT", "CLOSED_PAID", "CLOSED_CANCELLED"],
  PAYMENT_REQUEST_SENT: ["CALL_SCHEDULED", "PAYMENT_PROMISED", "INSTALLMENT_REQUESTED", "FINAL_NOTICE_SENT", "CLOSED_PAID", "CLOSED_CANCELLED"],
  CALL_SCHEDULED: ["CALL_COMPLETED", "CLOSED_PAID", "CLOSED_CANCELLED"],
  CALL_COMPLETED: ["PAYMENT_PROMISED", "INSTALLMENT_REQUESTED", "FINAL_NOTICE_SENT", "CLOSED_PAID", "CLOSED_CANCELLED"],
  PAYMENT_PROMISED: ["EMAIL_REMINDER_2_SENT", "CLOSED_PAID", "CLOSED_CANCELLED", "OVERDUE", "INSTALLMENT_PLAN_SENT", "MANUAL_REVIEW_REQUIRED", "FINAL_NOTICE_SENT"],
  INSTALLMENT_REQUESTED: ["INSTALLMENT_PLAN_SENT", "FINAL_NOTICE_SENT", "CLOSED_PAID", "CLOSED_CANCELLED"],
  INSTALLMENT_PLAN_SENT: ["INSTALLMENT_ACTIVE", "EMAIL_REMINDER_1_SENT", "PAYMENT_PROMISED", "MANUAL_REVIEW_REQUIRED", "FINAL_NOTICE_SENT", "CLOSED_PAID", "CLOSED_CANCELLED"],
  INSTALLMENT_ACTIVE: ["INSTALLMENT_BROKEN", "MANUAL_REVIEW_REQUIRED", "CLOSED_PAID", "CLOSED_CANCELLED"],
  INSTALLMENT_BROKEN: ["FINAL_NOTICE_SENT", "READY_FOR_LEGAL_ACTION", "CLOSED_PAID", "CLOSED_CANCELLED"],
  FINAL_NOTICE_SENT: ["INSTALLMENT_PLAN_SENT", "READY_FOR_LEGAL_ACTION", "CLOSED_PAID", "CLOSED_CANCELLED", "CLOSED_UNRESOLVED"],
  READY_FOR_LEGAL_ACTION: ["CLOSED_PAID", "CLOSED_CANCELLED", "CLOSED_UNRESOLVED"],
  CLOSED_PAID: [],
  CLOSED_CANCELLED: [],
  CLOSED_UNRESOLVED: []
};

export function canTransitionCase(from: CaseStatus, to: CaseStatus): boolean {
  return allowedTransitions[from]?.includes(to) ?? false;
}

export function assertCaseTransition(
  from: CaseStatus,
  to: CaseStatus
): void {
  if (from !== to && !canTransitionCase(from, to)) {
    throw new Error(`Unsupported case transition: ${from} -> ${to}.`);
  }
}

export const CASE_EVENT_TYPES = {
  caseCreated: "CASE_CREATED",
  invoiceParsed: "INVOICE_PARSED",
  manualReviewRequired: "MANUAL_REVIEW_REQUIRED",
  statusChanged: "STATUS_CHANGED",
  emailSent: "EMAIL_SENT",
  emailReceived: "EMAIL_RECEIVED",
  paymentCheckSent: "PAYMENT_CHECK_SENT",
  paymentReceivedConfirmed: "PAYMENT_RECEIVED_CONFIRMED",
  paymentNotReceivedConfirmed: "PAYMENT_NOT_RECEIVED_CONFIRMED",
  debtorReplyClassified: "DEBTOR_REPLY_CLASSIFIED",
  debtorReplyActioned: "DEBTOR_REPLY_ACTIONED",
  paymentPromiseCreated: "PAYMENT_PROMISE_CREATED",
  installmentProposed: "INSTALLMENT_PROPOSED",
  installmentActivated: "INSTALLMENT_ACTIVATED",
  installmentPaymentConfirmed: "INSTALLMENT_PAYMENT_CONFIRMED",
  installmentBroken: "INSTALLMENT_BROKEN",
  callRequired: "CALL_REQUIRED",
  automationPaused: "AUTOMATION_PAUSED",
  contactUpdated: "CONTACT_UPDATED",
  paymentMarkedPaid: "PAYMENT_MARKED_PAID",
  workflowStarted: "WORKFLOW_STARTED",
  workflowWaiting: "WORKFLOW_WAITING",
  legalPackagePrepared: "LEGAL_PACKAGE_PREPARED"
} as const;
