export const CASE_STATUSES = [
  "RECEIVED",
  "PARSED",
  "MANUAL_REVIEW_REQUIRED",
  "WAITING_FOR_DUE_DATE",
  "DUE_SOON",
  "OVERDUE",
  "EMAIL_REMINDER_1_SENT",
  "EMAIL_REMINDER_2_SENT",
  "PAYMENT_REQUEST_SENT",
  "CALL_SCHEDULED",
  "CALL_COMPLETED",
  "PAYMENT_PROMISED",
  "INSTALLMENT_REQUESTED",
  "INSTALLMENT_PLAN_SENT",
  "INSTALLMENT_ACTIVE",
  "INSTALLMENT_BROKEN",
  "FINAL_NOTICE_SENT",
  "READY_FOR_LEGAL_ACTION",
  "CLOSED_PAID",
  "CLOSED_CANCELLED",
  "CLOSED_UNRESOLVED"
] as const;

export type CaseStatus = (typeof CASE_STATUSES)[number];

export const TERMINAL_CASE_STATUSES: CaseStatus[] = ["CLOSED_PAID", "CLOSED_CANCELLED", "CLOSED_UNRESOLVED"];

const allowedTransitions: Record<CaseStatus, CaseStatus[]> = {
  RECEIVED: ["PARSED", "MANUAL_REVIEW_REQUIRED", "CLOSED_CANCELLED"],
  PARSED: ["WAITING_FOR_DUE_DATE", "MANUAL_REVIEW_REQUIRED", "CLOSED_CANCELLED"],
  MANUAL_REVIEW_REQUIRED: ["WAITING_FOR_DUE_DATE", "CLOSED_CANCELLED"],
  WAITING_FOR_DUE_DATE: ["DUE_SOON", "OVERDUE", "CLOSED_PAID", "CLOSED_CANCELLED"],
  DUE_SOON: ["OVERDUE", "CLOSED_PAID", "CLOSED_CANCELLED"],
  OVERDUE: ["EMAIL_REMINDER_1_SENT", "PAYMENT_PROMISED", "INSTALLMENT_REQUESTED", "CLOSED_PAID", "CLOSED_CANCELLED"],
  EMAIL_REMINDER_1_SENT: ["EMAIL_REMINDER_2_SENT", "PAYMENT_PROMISED", "INSTALLMENT_REQUESTED", "CLOSED_PAID"],
  EMAIL_REMINDER_2_SENT: ["PAYMENT_REQUEST_SENT", "PAYMENT_PROMISED", "INSTALLMENT_REQUESTED", "CLOSED_PAID"],
  PAYMENT_REQUEST_SENT: ["CALL_SCHEDULED", "PAYMENT_PROMISED", "INSTALLMENT_REQUESTED", "FINAL_NOTICE_SENT", "CLOSED_PAID"],
  CALL_SCHEDULED: ["CALL_COMPLETED", "CLOSED_PAID", "CLOSED_CANCELLED"],
  CALL_COMPLETED: ["PAYMENT_PROMISED", "INSTALLMENT_REQUESTED", "FINAL_NOTICE_SENT", "CLOSED_PAID"],
  PAYMENT_PROMISED: ["CLOSED_PAID", "OVERDUE", "FINAL_NOTICE_SENT"],
  INSTALLMENT_REQUESTED: ["INSTALLMENT_PLAN_SENT", "CLOSED_PAID", "CLOSED_CANCELLED"],
  INSTALLMENT_PLAN_SENT: ["INSTALLMENT_ACTIVE", "FINAL_NOTICE_SENT", "CLOSED_PAID"],
  INSTALLMENT_ACTIVE: ["INSTALLMENT_BROKEN", "CLOSED_PAID"],
  INSTALLMENT_BROKEN: ["FINAL_NOTICE_SENT", "READY_FOR_LEGAL_ACTION", "CLOSED_PAID"],
  FINAL_NOTICE_SENT: ["READY_FOR_LEGAL_ACTION", "CLOSED_PAID", "CLOSED_UNRESOLVED"],
  READY_FOR_LEGAL_ACTION: ["CLOSED_PAID", "CLOSED_CANCELLED", "CLOSED_UNRESOLVED"],
  CLOSED_PAID: [],
  CLOSED_CANCELLED: [],
  CLOSED_UNRESOLVED: []
};

export function canTransitionCase(from: CaseStatus, to: CaseStatus): boolean {
  return allowedTransitions[from]?.includes(to) ?? false;
}

export const CASE_EVENT_TYPES = {
  caseCreated: "CASE_CREATED",
  invoiceParsed: "INVOICE_PARSED",
  manualReviewRequired: "MANUAL_REVIEW_REQUIRED",
  statusChanged: "STATUS_CHANGED",
  emailSent: "EMAIL_SENT",
  emailReceived: "EMAIL_RECEIVED",
  paymentCheckSent: "PAYMENT_CHECK_SENT",
  paymentReceivedConfirmed: "PAYMENT_RECEIVED_CONFIRMED",
  paymentNotReceivedConfirmed: "PAYMENT_NOT_RECEIVED_CONFIRMED",
  debtorReplyClassified: "DEBTOR_REPLY_CLASSIFIED",
  paymentMarkedPaid: "PAYMENT_MARKED_PAID",
  workflowStarted: "WORKFLOW_STARTED",
  workflowWaiting: "WORKFLOW_WAITING",
  legalPackagePrepared: "LEGAL_PACKAGE_PREPARED"
} as const;
